version: '3.7'
services:
  iris:
    image: intersystemsdc/irishealth-community:latest
    ports:
      - "52773:52773"
      - "1972:1972"
    environment:
      - IRIS_USERNAME=admin
      - IRIS_PASSWORD=supersecret
